/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/


-- Find the total number of custormer  by countries
SELECT  country , COUNT(customer_id) AS Total_Customer 
FROM [gold.dim_customers]
GROUP BY country
ORDER BY Total_Customer DESC;

-- Find the total number of custormer  by Gender
SELECT  gender , COUNT(customer_id) AS Total_Customer 
FROM [gold.dim_customers]
GROUP BY gender
ORDER BY Total_Customer DESC;

-- Find the total productnumber by category

SELECT category , COUNT(product_id) AS Total_product
FROM [gold.dim_products]
GROUP BY category
ORDER BY Total_product DESC;

-- AVG costs in each Category

SELECT  category, AVG(cost) as avg_cost
FROM [gold.dim_products] 
GROUP BY category
ORDER BY avg_cost DESC

-- Total revenue generated for each category
SELECT  P.category, SUM(f.sales_amount) AS Total_revenue
FROM [gold.fact_sales] as f
LEFT JOIN [gold.dim_products] AS P
on p.product_key=f.product_key
GROUP BY p.category
ORDER BY Total_revenue desc;


-- Total revenue generated by each customer
SELECT c.customer_key,c.first_name , c.last_name ,sum(f.sales_amount) as Total_revenue
FROM [gold.fact_sales] as f
LEFT JOIN [gold.dim_customers] AS c
ON f.customer_key=c.customer_key
GROUP BY c.customer_key,c.first_name, c.last_name
ORDER BY Total_revenue DESC

-- What is the distribution of sold item across countries

SELECT c.country ,sum(f.quantity ) as Total_sold_item
FROM [gold.fact_sales] as f
LEFT JOIN [gold.dim_customers] AS c
ON f.customer_key=c.customer_key
GROUP BY c.country
ORDER BY Total_sold_item DESC

